### ISSUE TITLE
Add "Start at login" option

### ISSUE THREAD

**Issue by dmarcotte** [dmarcotte/easy-move-resize#1]
It would nice to let users select "Start at login" from within the app (default to `true`?).

**Workaround:** Until this is implemented, you can enable launching Easy Move+Resize at login in `System Preferences -> Users & Groups` by adding it to the `Login Items` tab for your user

**Comment by dmarcotte** [comment]
After years of consideration (wow does time fly sometimes...), I think I'm ready to commit to not adding anything for this use case that is so well supported by the built-in OS functionality:

Enable launching **Easy Move+Resize** at login in `System Preferences -> Users & Groups` by adding it to the `Login Items` tab for your user

**Comment by syabro** [comment]
@dmarcotte probably add a menu item "how to install on login"?
