### ISSUE TITLE
trackpad support

### ISSUE THREAD

**Issue by cedricbastin** [dmarcotte/easy-move-resize#10]
Hey, great tool! =) Thanks a lot!
It would be great if this would work with the trackpad:
right now: Ctrl-click is a right click
however to trigger your tool **Ctrl-Cmd-Click** already uses the **Ctrl** key...
I think the best option would be to add: **Cmd + Alt + Ctrl + Left** Mouse to **resize**

Thanks a lot, Cedric

**Comment by dmarcotte** [comment]
Hey @cedricbastin, thanks for the note.  I'll take this as a +1 for https://github.com/dmarcotte/easy-move-resize/issues/2.

(It's clearly not how you like to work, but a two-finger click should also get you a right click on your trackpad, allowing you to use the current resize shortcut)

**Comment by cedricbastin** [comment]
On the trackpad you can do a right-click using 2 fingers, however you CANNOT do a right-drag!!
So currently with my Magic Trackpad only I cannot use the resize functionality at all!
