### ISSUE TITLE
Right/Left Click Optional

### ISSUE THREAD

**Issue by harrisitservices** [dmarcotte/easy-move-resize#16]
Is there any way you could allow for modifier keys without clicks. I would see it working like this. Press modifier1 (fn+control+command) and move the mouse to resize. Press modifier2 (fn+alt+cmd) and move mouse to move. I generally use the trackpad and the clicking can be painful.

**Comment by rajpaulbagga** [comment]
Just a thought. Have you tried turning on "Three finger drag" in the Trackpad preferences? (I see it in OS X Yosemite; can't speak to other versions.)  It at least allows moving the window using the modifier and the trackpad without clicking.

**Comment by dmarcotte** [comment]
Going to close this as a dupe of https://github.com/dmarcotte/easy-move-resize/issues/21, but the good news is it's looking fairly likely this feature will be added at some point.
