### ISSUE TITLE
drag without clicking trackpad

### ISSUE THREAD

**Issue by CodisRedding** [dmarcotte/easy-move-resize#21]
How easy would it be to mimic what zooom2 does and allows windows to be dragged without having to actually click the trackpad and dragging, but instead just keys + dragging?

**Comment by unphased** [comment]
I really want this feature. 

This program works much better than BTT's current implementation (which is already quite buggy even prior to Sierra). It is buttery smooth and does not lose track of the dragged window. But forcing the user to actually click makes it much more cumbersome and less efficient.

**Comment by eun-ice** [comment]
I also look for an alternative to Zoom/2. This does almost what Zoom/2 did, you just have to click on right/left mouse button. That's a small usability issue on desktop but on a macbook with a touchpad it's not usable at all.

Once this is solved, I know quite a few users of Zoom/2 who will immediately use this project.

**Comment by unphased** [comment]
I've never used zooom/2, and took a bit of searching to find out what it is, but I have been quite happy with Better Touch Tool's equivalent functionality. It's hidden in the settings. But it works without requiring clicking. It's a big deal. 😊

**Comment by elFua** [comment]
A workaround is described here: https://github.com/dmarcotte/easy-move-resize/pull/25#issuecomment-372021683

**Comment by stevelacey** [comment]
Yes, this and #36 would give you feature parity (well, window moving/resizing parity) with HyperDock too

**Comment by elFua** [comment]
After having waited for months for hover-resize to be added, I was pleased to discover that the  @feinstruktur's fork does exactly that. It compiled without issue with Xcode and can be configured to work exactly the same way as bettertouchtool.

The changes you want are in the branch named `move-only-tracking`.

I followed these steps:

1. `git clone git@github.com:feinstruktur/easy-move-resize.git`
1. `cd easy-move-resize`
1. `git checkout move-only-tracking`
1. `open easy-move-resize.xcodeproj` (or double-click the project file in Finder)
1. Click the **Run** button in xcode: this should build and run the app.
1. In terminal enter `open ~/Library/Developer/Xcode/DerivedData` (or use Finder) and locate the folder that starts with `easy-move-resize` — it will contain the app bundle **Easy Move+Resize.app** which you can copy to /Applications

A zipped binary version that I compiled is [here](https://www.dropbox.com/s/anp2aa0ypy87fhz/EasyMoveResize.zip?dl=1) (_you probably should not install random binaries, but in case you don't care or don't feel like building it yourself you have it here_).

**Comment by finestructure** [comment]
@elFua thanks - I'm glad this is proving useful :) Having received feedback from @dmarcotte about forking this in #41 I'll look into cleaning this up into a "hover mode only" fork.

**Comment by elFua** [comment]
@finestructure: thanks for the heads-up! i've updated the repo, even though github does indeed redirect to the updated account name.

**Comment by reverie** [comment]
Just wanted to say thank you so much to @elFua and @finestructure! Working perfectly.

**Comment by finestructure** [comment]
FYI, I've just pushed the first release of Hummingbird, with the "hover" behaviour: https://github.com/finestructure/Hummingbird/releases/tag/2.0.0

**Comment by CodisRedding** [comment]
@finestructure should there be a compiled application file in the ....app.zip? (i'll talk over on your repo if we continue on)

**Comment by finestructure** [comment]
@CodisRedding Yes, just unzipping the file should do the trick! Please open an issue over in my repo if it’s not working, happy to take a look.

**Comment by dmarcotte** [comment]
Closing in favor of https://github.com/dmarcotte/easy-move-resize/issues/50
