### ISSUE TITLE
not working anymore?

### ISSUE THREAD

**Issue by chr0max** [dmarcotte/easy-move-resize#23]
Can´t get it to work with Sierra 10.12.5!?

Is it like other tools that manipulate the GUI and it´s not working since Sierra?

**Comment by dmarcotte** [comment]
Hey @chr0max, can you give me a bit more color on what you're seeing?  Sierra (including 10.12.5) works great as far as I know.

Is "Easy Move+Resize" checked in `System Preferences->Security & Privacy->Privacy->Accessibility`?

![screen shot 2017-06-15 at 10 23 27 am](https://user-images.githubusercontent.com/711001/27193718-ce812d5c-51b4-11e7-9002-a48f03d72258.png)

**Comment by chr0max** [comment]
Hi,
thanks for your response. Yes, its everything fine there. Looks like yours. Does it works on your MacOS with newest update?

**Comment by dmarcotte** [comment]
@chr0max wonder if you're bumping up against the bug reported here? https://github.com/dmarcotte/easy-move-resize/issues/24.  Can you try "Reset to Defaults"?

**Comment by dmarcotte** [comment]
Optimistically closing this as a dupe of https://github.com/dmarcotte/easy-move-resize/issues/24.  @chr0max please feel free to let me know I've missed something here.
