### ISSUE TITLE
Feature request: app blacklist

### ISSUE THREAD

**Issue by dzg** [dmarcotte/easy-move-resize#27]
First, this is awesome! Thank you!

This is not an issue per se, but didn't know where to suggest...

It would be great if one could blacklist certain apps (such as Adobe) to disable the feature when using those apps.

Thanks again

**Comment by dmarcotte** [comment]
Glad you're enjoying the app @dzg!  This is a fine place to suggest this, and a really neat idea.  Will keep it in mind, and would welcome contributions that added this ability.

**Comment by dmarcotte** [comment]
Implemented in #72, and released in version 1.5.0!
