### ISSUE TITLE
Work bad with mouse

### ISSUE THREAD

**Issue by wuyihao14** [dmarcotte/easy-move-resize#32]
It works well with trackpad.
But it works bad with mouse. Window dragging is like slow motion, there's delay for window to follow my mouse.

**Comment by dmarcotte** [comment]
@wuyihao14 have you tried the latest release?  https://github.com/dmarcotte/easy-move-resize/releases/tag/1.2.0.

This sounds like exactly the issue that release solves.  Going to optimistically close this, but please let me know if I'm wrong and I'd be glad to reopen and have another look.
