### ISSUE TITLE
Feature request: Add a another modifier key for resize

### ISSUE THREAD

**Issue by cfarvidson** [dmarcotte/easy-move-resize#36]
I think that **Easy Move+Resize!** is great! 😃 

With that said I find it hard to resize windows on my trackpad with <modifier key> + two fingers (the right click).

I would be great to have a second alternative when you use a trackpad. Let's say that you press down <modifier key> + <modifier key 2> to start resizing the window?

**Comment by kevinob11** [comment]
I'd love this, two fingers on the trackpad can be pretty rough. This would completely replace the one feature I own hyperdock for.

**Comment by finestructure** [comment]
Check out my fork of easy-move-resize which I'm in the process of releasing. It does exactly that.

Here's the release branch with a video of what this looks like: https://github.com/finestructure/easy-move-resize/tree/release-prep

**Comment by kevinob11** [comment]
@finestructure LGTM!

**Comment by cfp2000** [comment]
@finestructure Hummingbird looks awesome! Great job!

The feature that I would like is the ability to use modifier + mouse if available and just modifier keys on a trackpad. 

For me the alt + right and left mouse is working great. 

But I would also like to use command + shift on my trackpad to trigger a move. And maybe command + shift + ctrl to resize.

**Comment by finestructure** [comment]
Thanks, @cfp2000 . Given how much I'm struggling to even get out a proper release (and how much the projects have diverged), it's quite unlikely that either will do what the other does.

However, I wonder if you could run both - as long as you use different control keys. EMR for mouse operation and Hummingbird for the trackpad. Might be worth a try!

**Comment by finestructure** [comment]
FYI, I've just pushed the first release of Hummingbird, with the "hover" behaviour: https://github.com/finestructure/Hummingbird/releases/tag/2.0.0

**Comment by kevinob11** [comment]
Awesome, just tested and it works perfect, thanks!

Kevin OBrien
Praece Consulting | www.praece.com
direct: (253) 740-8838
main: (253) 293-5783

**Comment by cfp2000** [comment]
I tested Hummingbird and It works like a charm. 

Great work @finestructure!

**Comment by d33rforce** [comment]
+1 to this - hummingbird and @finestructure are great, but for those of us looking for both click behaviour as well as alternate modifier for resize - think this could be possible?

**Comment by dmarcotte** [comment]
Closing in favor of https://github.com/dmarcotte/easy-move-resize/issues/69
