### ISSUE TITLE
Resize with middle mouse button

### ISSUE THREAD

**Issue by frenchie1980** [dmarcotte/easy-move-resize#38]
Hi,

My X11 default behaviour is to resize with the middle mouse button instead of right. Could you possibly add the ability to customise this to your preference?

**Comment by wad** [comment]
This too, please!

**Comment by patchon** [comment]
Haha, I came here for this!

**Comment by patchon** [comment]
Hey guys, 

Just wanted to let you that there is a build of this feature here https://github.com/patchon/easy-move-resize/raw/master/build/Easy%20Move%2BResize 

Hopefully this gets merged into master eventually.

**Comment by dmarcotte** [comment]
This has been released in 1.4.0: https://github.com/dmarcotte/easy-move-resize/releases/tag/1.4.0

Thanks again @patchon!

**Comment by patchon** [comment]
> This has been released in 1.4.0: https://github.com/dmarcotte/easy-move-resize/releases/tag/1.4.0
> 
> Thanks again @patchon!

Awesome! 😃 🎉
