### ISSUE TITLE
Feature request: put focus on window when moving/resizing it

### ISSUE THREAD

**Issue by lucianovdveekens** [dmarcotte/easy-move-resize#40]
It would be nice if the focus would change to the window you're currently dragging or resizing, like the way it works in Gnome, because currently when you're trying to move a window behind another one, it remains hidden and you cannot really see what you're doing.

There's no need for this to be the default functionality, but it would be cool if it's an option.

**Comment by wad** [comment]
Yes please!

**Comment by dmarcotte** [comment]
This can be turned on in the latest release: https://github.com/dmarcotte/easy-move-resize/releases/tag/1.3.0.  Thanks @CianMclennan for implementing!
