### ISSUE TITLE
Intermittently stops working

### ISSUE THREAD

**Issue by orincatali** [dmarcotte/easy-move-resize#43]
MacOS High Sierra 10.13.6. When I reboot, all is well. But eventually it will just stop functioning. Nothing, not even a complete uninstall/reinstall will get it to work again until I reboot, and sometimes that doesn't even work. Tried changing key combinations; thinking that it was a conflict. Also tried closing out some apps that I thought might conflict, like Magnet, Smooze, BetterTouchTool, etc... Still nothing.

**Comment by dmarcotte** [comment]
Apologies for the delayed response here, @dicetomato.  Is this still an issue?  And if yes, are you certain you're running the [latest version](https://github.com/dmarcotte/easy-move-resize/releases/tag/1.2.0)?

**Comment by dicetomato** [comment]
Forgive me but after reporting the issue I realized that BetterTouchTool had a similar feature so I've been using that. I do think yours is a more elegant solution so I re-downloaded the latest version. So far it's working but remember, my issue was intermittent so I'll report back here if it happens again. Currently using ALT+CMD as my shortcut keys.

**Comment by dicetomato** [comment]
Hi @dmarcotte, It looks like the issue returned. I used it all yesterday and took my laptop home with me, this morning when I plugged my Macbook Pro into my dock, I tried to use my hotkeys and it's not working. The app is on and activated. Even if I close and re-open now it doesn't recognize the hotkeys. I believe if I restart, it will work again; that's what I used to do.

**Comment by dmarcotte** [comment]
So strange... and you're still on High Sierra 10.13.6?  Any interesting looking output you can spot in the Console app by any chance?

**Comment by dicetomato** [comment]
Nothing that jumps out at me, could be my inexperience with the console app though. Yes I'm on High Sierra 10.13.6

**Comment by dmarcotte** [comment]
So strange.  Next time this happens, I'm curious:

- what does `defaults read org.dmarcotte.Easy-Move-Resize ModifierFlags` output in a terminal?
- does choosing "Reset to Defaults" from the system tray icon fix your issue?

**Comment by dicetomato** [comment]
Just happened again. That command shows:
`The domain/default pair of (org.dmarcotte.Easy-Move-Resize, ModifierFlags) does not exist`

Resetting to defaults does nothing :(.

**Comment by simgust** [comment]
Just happened to me as well. Resetting to default, unchecking and checking modifiers again, quitting and relaunching, nothing works! :(

**Comment by finestructure** [comment]
Try removing and re-adding it to the accessibility section in System Preferences -> Security & Privacy -> Privacy

**Comment by simgust** [comment]
Testing again now after a few hours it seems to have started working again. But I’ll keep that in mind if it happens again.

**Comment by dmarcotte** [comment]
Doing a bit of cleanup, and going to close this one, but happy to reopen and dig some more if it rears its head again.  This must have been so annoying.  I wish we'd gotten to the bottom of it.

**Comment by calvinwyoung** [comment]
@dmarcotte Unfortunately I've also been experiencing this issue for some time now (glad to know I'm not the only one!). When I run `defaults read org.dmarcotte.Easy-Move-Resize ModifierFlags`, I get the following result:

```
The domain/default pair of (org.dmarcotte.Easy-Move-Resize, ModifierFlags) does not exist
```

Resetting to default, quitting/restarting, etc. don't work either. Is there anything else I can do to help debug this?
