### ISSUE TITLE
doesn't work with emacs

### ISSUE THREAD

**Issue by smoofra** [dmarcotte/easy-move-resize#48]
For some reason it can't move or resize emacs.   I'm using the build from here: <https://emacsformacosx.com>

**Comment by tigger04** [comment]
same - in fact it's all XQuartz applications (X11 on mac :(

**Comment by dmarcotte** [comment]
Yeah, sorry y'all.  This uses the accessibility API to its moving and resizing, so we inherit the limitations built into that, which apparently includes not playing nice with the X11 stuff.

**Comment by cpiro** [comment]
fwiw, YAMAMOTO Mitsuharu's Mac port of Emacs integrates with macOS better than any other build I've seen. It's worked well with easy-move-resize for me for a while now. in homebrew: [railwaycat/emacsmacport/emacs-mac](https://github.com/railwaycat/homebrew-emacsmacport/blob/HEAD/Formula/emacs-mac.rb).

**Comment by dmarcotte** [comment]
Ah, cool.  Thanks @cpiro
