### ISSUE TITLE
Cannot start on 10.15.6

### ISSUE THREAD

**Issue by mgenet** [dmarcotte/easy-move-resize#54]
Hello,

After this week's update to MacOS I am getting the message:
`“Easy Move+Resize.app” can’t be opened because Apple cannot check it for malicious software.
This software needs to be updated. Contact the developer for more information.
Homebrew Cask downloaded this file on 11 September 2020 from github.com.`
Is there going to be an update? Thank you so much—without this app I could not use MacOS…

Martin

**Comment by dmarcotte** [comment]
Hey @mgenet, so glad this app has been a help.  You should be able to get things going again following the instructions [here](https://github.com/dmarcotte/easy-move-resize/issues/7#issuecomment-668671150).  Let me know if that doesn't get you sorted!

**Comment by mgenet** [comment]
It worked! (For some reason in System Preferences > Security & Privacy > Privacy > Accessibility I had to remove Easy Move+Resize and add it again…) Thanks!
