### ISSUE TITLE
Adding exclusions

### ISSUE THREAD

**Issue by becauseim** [dmarcotte/easy-move-resize#55]
Unfortunately, without the ability to exclude certain programs can not be used this app, as all modifiers in conjunction with the cursor used in some editors. I hope this opportunity will appear in the next version.

**Comment by trustin** [comment]
It would be nice at least if well know window managers/switchers are ignored, e.g.

- [Alt-Tab](https://alt-tab-macos.netlify.app/)
- [Context](https://contexts.co/)
- [HyperSwitch](https://bahoom.com/hyperswitch)
- [HyperDock](https://bahoom.com/hyperdock)
- [MissionControl Plus](https://www.fadel.io/missioncontrolplus)
- [Optimal Layout](http://most-advantageous.com/optimal-layout/)
- [Switch](https://github.com/numist/Switch)
- [WindowSwitch](https://www.noteifyapp.com/windowswitcher/)
- [Witch](https://alt-tab-macos.netlify.app/)

**Comment by becauseim** [comment]
pity that the developer can not add such a simple condition in the program, will have to abandon the idea

**Comment by dmarcotte** [comment]
Support added in #72, released in 1.5.0

**Comment by trustin** [comment]
Nice! Thanks a lot for adding this useful feature. 🙇 Would there be any change we could have the sensible default, excluding [the above apps](https://github.com/dmarcotte/easy-move-resize/issues/55#issuecomment-698225225) out of the box?
