### ISSUE TITLE
Buggy menu bar icon on multi-display setup

### ISSUE THREAD

**Issue by Rabattkarte** [dmarcotte/easy-move-resize#58]
Hi, whenever I have a second display connected, the menu bar item on the "inactive display" will just display a grey block instead of the "two arrows"-icon. Please see attached screenshots.

Inactive display menu bar:
![Inactive display menu bar](https://i.imgur.com/gdHZJUU.png)

Active display menu bar:
![Active display menu bar](https://i.imgur.com/3p6IS6X.png)

Let me know if you need any more information provided.

Cheers.

**Comment by dmarcotte** [comment]
Thanks for this report @Rabattkarte.  I believe the icon change in the [latest release](https://github.com/dmarcotte/easy-move-resize/releases/tag/1.4.1) should fix this.  Let me know if you see anything else, and thanks again.
