### ISSUE TITLE
Can’t be opened because Apple cannot check it for malicious software

### ISSUE THREAD

**Issue by kevinkepp** [dmarcotte/easy-move-resize#59]
Getting the following error when trying to open the app since I upgraded with brew a couple of days ago.

`“Easy Move+Resize.app” can’t be opened because Apple cannot check it for malicious software.`

<img width="532" alt="Screen Shot 2020-11-17 at 10 44 00" src="https://user-images.githubusercontent.com/787153/99373732-09e98f00-28c2-11eb-8571-25917b114620.png">

**Comment by rha-iag** [comment]
worked here, remove it from the system control center list and add it again

**Comment by kevinkepp** [comment]
Found the solution. I had to open `Security & Privacy` settings and unlock the app as described here:
https://support.apple.com/en-us/HT202491
