### ISSUE TITLE
How to build/run from source?

### ISSUE THREAD

**Issue by joaotavora** [dmarcotte/easy-move-resize#61]
I like this program and use it daily. The other day, I cloned this repo and opened the `xcodeproj` in Xcode, hoping to add a few features, like killing windows instantly when control+alt+command+middle-clicking on them.

So I naively clicked play in Xcode hoping for that to work.  The build succeeded alright, but the program didn't run.  I'm heavily suspicious of a failure to request the "Ability to control the computer" from the "Security & Privacy" section in Preferences.   To test it, I probably have to go find the binary in some far away directory, re-add it to that dialog.  It's a very clumsy cycle.

I wish I could just bypass it and/or tell Xcode that I'm a developer and I know what I'm doing.   How do you, @dmarcotte , develop/run this thing?

**Comment by dmarcotte** [comment]
Hey @joaotavora,so glad the program is helping you!  And it's great that you're trying to build and run.  I think I can help out here:

You can indeed just click play in Xcode, but to give the Accessibility API permission, you need to click "Open System Preferences" in the dialog that comes up, then in the "Security & Privacy" window that comes up, uncheck then re-check Easy Move+Resize.  On next run, it'll run.

Unfortunately, there's some somewhat painful news: you need to do this after every time you change the program.  Such a pain.  This is new (previously when developing, you would give _Xcode_ access to the Accessibility API, and that would simply persist).  If I find a workaround I'll update here (if anyone reading this has a trick, please chime in!), but in the meantime, you'll need to do the privacy checkmark dance every every time you edit the program.

**Comment by joaotavora** [comment]
Thanks for the info @dmarcotte , but indeed what terrible terrible news. There has to be some super-user way of bypassing this...
