### ISSUE TITLE
Mouse cursor doesn't move while dragging/resizing

### ISSUE THREAD

**Issue by dluc** [dmarcotte/easy-move-resize#68]
OS: MacOS Big Sur 11.3.1

While dragging or resizing a window, the mouse cursor remains frozen in the original position, until the keyboard keys or the mouse keys are released.  Once released the cursor appears where it's supposed to be. 

In other words, the cursor position is changing in memory but not rendered on screen, so it looks like the mouse is not working.

**Comment by dluc** [comment]
![2021-05-31_23-56-40](https://user-images.githubusercontent.com/371009/120280583-b8588e80-c26c-11eb-82a7-919d1e41f8a6.gif)

**Comment by dmarcotte** [comment]
Fascinating.  Which modifiers are you using?  I have Big Sur 11.3.1, and this didn't reproduce on my machine with the handful of modifiers I tried.

**Comment by dluc** [comment]
I was testing the modifiers to see if that might be the case (I use only `Alt`), and I just noticed that the error occurs only when I have a second screen plugged in (via usb-c). It happens on both the main and the external screen (I tried multiple modifiers, e.g. Alt, Cmd+Alt, Cmd+Alt+Ctrl), and as soon as I unplug the external monitor everything works correctly. 
Model: MacBook Pro (15-inch, 2018); Graphics: Radeon Pro 560X 4 GB, Intel UHD Graphics 630 1536 MB.

**Comment by dmarcotte** [comment]
Ah, interesting! Thanks for narrowing that down. 

I use an external monitor all the time, and don't see this, so it's got me curious: if you disable (or even uninstall?) Easy Move+Resize, does modifer+drag still behave like that? Wondering if this is an OS rendering thing with your particular monitor rather than something EMR-specific.

**Comment by dluc** [comment]
I was about to test your last ask, but the problem disappeared, everything works as expected with Alt now. It's possible that a recent OS upgrade to 11.4 addressed that :-) 
Thanks!

**Comment by dmarcotte** [comment]
Ah, brilliant!  Thanks for the update, @dluc

**Comment by guneet-xyz** [comment]
Just installed this application. I'm facing the same issue as @dluc 

https://github.com/user-attachments/assets/8a45b605-22b6-4216-bc07-e0b1c6735e39

**Comment by guneet-xyz** [comment]
> I was testing the modifiers to see if that might be the case (I use only `Alt`), and I just noticed that the error occurs only when I have a second screen plugged in (via usb-c). It happens on both the main and the external screen (I tried multiple modifiers, e.g. Alt, Cmd+Alt, Cmd+Alt+Ctrl), and as soon as I unplug the external monitor everything works correctly. Model: MacBook Pro (15-inch, 2018); Graphics: Radeon Pro 560X 4 GB, Intel UHD Graphics 630 1536 MB.

Same behavior for me as well.
