### ISSUE TITLE
give window focus

### ISSUE THREAD

**Issue by xortim** [dmarcotte/easy-move-resize#7]
The window receiving the easy move+resize action should receive focus and be brought to the front. When moving the window around with a lot of other windows it can get lost behind others. This would also make it behave more like KDE/Gnome/Unity and other DEs/WMs that have this functionality out of the box.

**Comment by gcbw** [comment]
👍 agree that it should be an extra option.

on most linux WMs with "bring window to front" option set to off, modifier+leftMouse+moving a window won't change it Z position. But just modifier+leftMouse without moving will bring it to front and focus.

**Comment by oliverjensen-wk** [comment]
+1 I'd like this option -- it feels strange to me to drag a window behind another.

**Comment by rmetzger** [comment]
Big +1 on this idea!
Would be great to add it as an option!

**Comment by yew1eb** [comment]
:+1:

**Comment by sebastienvermeille** [comment]
Yes definitly need this option :) some linux have it like ubuntu 📦

**Comment by wad** [comment]
Yes please!

Also, thanks **SO FREAKIN' MUCH** for building this tool. I'm moving from Ubuntu to Mac for work, and finding this tool has saved my day!

**Comment by dmarcotte** [comment]
This can be turned on in the latest release: https://github.com/dmarcotte/easy-move-resize/releases/tag/1.3.0.  Thanks @CianMclennan for implementing!

**Comment by wad** [comment]
Thanks so much! I just upgraded with `brew cask upgrade easy-move-plus-resize`, but when I run it, I get an error saying that Apple can't check the software: "... can’t be opened because Apple cannot check it for malicious software."

![Screen Shot 2020-08-03 at 9 24 41 AM](https://user-images.githubusercontent.com/319180/89199325-9f5b5000-d56b-11ea-9c9a-eb2daf30c10e.png)

Thoughts?

**Comment by dmarcotte** [comment]
Ah, glad you're sorted @wad.  Here's a bit more detail on what's needed in case others stumble on this:

To fix: Click `OK` in "can't be opened" dialog, then open `System Preferences->Security & Privacy`, select the `General` tab, and you see the option to "`Open Anyway`".  Clicking that will allow the program to run (and this choice will persist).
<img width="780" alt="Screen Shot 2020-08-04 at 8 36 09 AM" src="https://user-images.githubusercontent.com/711001/89313832-db56e980-d62d-11ea-86d2-a71d9835ffc3.png">
