### ISSUE TITLE
Doesn't work with all applications (probably X11 applications?)

### ISSUE THREAD

**Issue by alexanderadam** [dmarcotte/easy-move-resize#70]
[KeePassXC](https://keepassxc.org/) doesn't seem to be draggable for example.

**PS:** Thank you so much for this! 🙌  I guess everyone coming from a FOSS window manager is missing this on other interfaces. 😉

**Comment by dmarcotte** [comment]
Thanks for the note, @alexanderadam.  You're right about the X11 limitation unfortunately, see some more details [here](https://github.com/dmarcotte/easy-move-resize/issues/48#issuecomment-802441762).  Hope this app is helping you otherwise!
