### ISSUE TITLE
Slow / jerky moving and resizing

### ISSUE THREAD

**Issue by sshock** [dmarcotte/easy-move-resize#74]
This app works perfectly and is a lifesaver!  But I have noticed that when moving or resizing a window it is noticeably slower / jerky / jaggedy than the normal way.

The normal moving and resizing is just smooth as butter.  Is there is no way to make easy-move-resize also smooth?

**Comment by brooksilg** [comment]
A solution is being discussed in this issue

https://github.com/dmarcotte/easy-move-resize/issues/33

**Comment by dmarcotte** [comment]
Thanks for the note, @sshock!  Going to close this in favor of #33, so please follow along there.
