### ISSUE TITLE
Asks for Accessibility but already has it after update to 1.5.0

### ISSUE THREAD

**Issue by Jeff-Walker** [dmarcotte/easy-move-resize#79]
I've been using the app for a while now, but I guess I updated it via brew and now it when it starts, it requests accessibility permissions. When I look at the settings, it already has it. 

I've tried unchecking and checking it, reinstalling with brew and uninstalling it, then installing it. Same thing. If I choose "deny", the app doesn't start.

**Comment by dmarcotte** [comment]
Thanks @Jeff-Walker, @uzak.  I was able to reproduce this (not sure if they matter but here are some repro details: I used `brew upgrade --cask easy-move-plus-resize` and was on new Apple silicon).  However, I was also able to fix the issue as follows:

**Workaround:**
- In `System Preferences -> Security & Privacy`, on the `Privacy` tab under `Accessibility`, click the **Easy Move+Resize** entry to select it, then click the minus `-` button at the bottom of the list
- Now, relaunch **Easy Move+Resize** and re-enable it in `Accessibility`
- Version 1.5.0 worked for me after this

Please let me know if that sorts y'all out, and thanks again for reporting.

**Comment by uzak** [comment]
Hello @dmarcotte. It worked fine and solved the problem for me. Thank you!

**Comment by Jeff-Walker** [comment]
Solved the problem for me too. Thanks for the help.

**Comment by dmarcotte** [comment]
Thank you both!

**Comment by pnyccz** [comment]
> Please let me know if that sorts y'all out, and thanks again for reporting.

This works, with a minor drawback. When I remove the app from Accessibility settings, both the keyboard and mouse stop working. The mouse pointer moves, but I can't type or click. I have to power-cycle the Mac to regain control. Re-adding the app afterward resolves the issue.

**Comment by hoshsadiq** [comment]
The documented workaround didn't work for me for some reason. If anyone finds this in the future, with the help of Claude I was able to run `tccutil reset Accessibility`, which cleared the cache but better I guess? This did clear all accessibility permissions, not just Easy Move+Resize. Not a huge issue for me.
