### ISSUE TITLE
Not as smooth as built-in Move and Resize

### ISSUE THREAD

**Issue by sbissonnette** [dmarcotte/easy-move-resize#80]
I LOVE this project, but the title says it all.

Visually when moving and resizing a window, there is very slight lag compared to builtin movement.
Do you think it would be possible to fix that?

**Comment by dmarcotte** [comment]
Thanks, @sbissonnette, so glad the project's helped you!  Improving smoothness is being discussed in https://github.com/dmarcotte/easy-move-resize/issues/33, so please follow along there.
