### ISSUE TITLE
Unable to run on macOS Montery 

### ISSUE THREAD

**Issue by AObuchow** [dmarcotte/easy-move-resize#84]
I just got a MacBook and wanted to try this software out, but unfortunately I got the following error when trying to run it:
![Screen Shot 2022-07-14 at 12 32 49 AM](https://user-images.githubusercontent.com/10300119/178899454-265bc2ba-bf78-4d8f-9171-6ec264a7f228.png)

Hope this can be fixed as I'd love to resize windows in the way I'm used to on KDE Plasma :) Thank you!

**Comment by dmarcotte** [comment]
Hi @AObuchow, so glad you're trying out the project.

I believe you should be able to bypass this by right-clicking on the app in Finder and choosing `Open` from the pop-up—that seems to reassure MacOS that you're not opening it by accident, and you should get a new prompt that allows you to open it in spite of the warning.

Alternatively, folks have reported that running `xattr -dr com.apple.quarantine /Applications/Easy\ Move+Resize.app` on the command line fixes this.

Going to optimistically close this as resolved, but please feel free to ask for more help if you're not actually sorted!  We'll get you up and running.

**Comment by AObuchow** [comment]
> Hi @AObuchow, so glad you're trying out the project.
> 
> I believe you should be able to bypass this by right-clicking on the app in Finder and choosing `Open` from the pop-up—that seems to reassure MacOS that you're not opening it by accident, and you should get a new prompt that allows you to open it in spite of the warning.
> 

Thank you so much, this fixed it :) 
Everything works as expected - happy to have this functionality in macOS now :)

One small thing I noticed: when moving around a window with easy-move-resize, it seems to be a bit less smooth than when I use 3 fingers on my trackpad to move around a window.

I don't know if this is just my perception, or if this is a side-effect of how the window movement is implemented (and maybe it's not possible to improve it). However, I wanted to bring it up just in-case you've noticed the same behaviour. I can make a new issue for this as well :)

**Comment by abondarev84** [comment]
this is an issue again with Ventura 13.4 (neither of the above mentioned solutions worked).
