### ISSUE TITLE
Can't start Application anymore on Ventura 13.1

### ISSUE THREAD

**Issue by fullheart** [dmarcotte/easy-move-resize#88]
After the OS upgrade to `macOS Ventura 13.1 (22C65)` I can't anymore star the app.

I get this message from Apple - see Screenshot:

![image](https://user-images.githubusercontent.com/25485618/209115285-332394cd-4623-4c41-8120-babd56b78379.png)

Version Information
```sh
brew info easy-move-plus-resize

==> easy-move-plus-resize: 1.5.0
https://github.com/dmarcotte/easy-move-resize
/opt/homebrew/Caskroom/easy-move-plus-resize/1.5.0 (130B)
From: https://github.com/Homebrew/homebrew-cask/blob/HEAD/Casks/easy-move-plus-resize.rb
==> Name
Easy Move+Resize
==> Description
Utility to support moving and resizing using a modifier key and mouse drag
==> Artifacts
Easy Move+Resize.app (App)
==> Analytics
install: 120 (30 days), 364 (90 days), 1,588 (365 days)
```

Thank you for your support and for this great tool.

**Comment by dmarcotte** [comment]
Hi @fullheart, so glad this project has been of help to you.  These instructions should get you up and running: https://github.com/dmarcotte/easy-move-resize/issues/84#issuecomment-1184946746.  Let me know if not and we'll get you sorted.

**Comment by fullheart** [comment]
@dmarcotte Thx. I found an other solution. Allowed the blocked app here the the System Settings:

![image](https://user-images.githubusercontent.com/25485618/209297091-cc3bf5ff-323e-4d77-8f1c-77740f217156.png)

Afterwards I have to remove and add the App in the System Settings under Privacy -> Accessibility:
![image](https://user-images.githubusercontent.com/25485618/209297344-e8fd3282-50ae-4d05-88ce-3c18d277bd32.png)

Now the app works properly again.

**Comment by dmarcotte** [comment]
Thanks @fullheart!
