### ISSUE TITLE
Latest version seems to have an issue

### ISSUE THREAD

**Issue by jordanpwalsh** [dmarcotte/easy-move-resize#90]
The latest version that updated a day or two ago keeps prompting the Mac OS security prompt for accessibility controls on launch and is never able to get pas it.

**Comment by JimMcHale** [comment]
Having same issue on ventura 13.4 beta; sent apple feedback in case it is a beta and not the app issue. 
I am running version 1.6.0 installed by brew (its the latest version in brew)

**Comment by dmarcotte** [comment]
Hi @jordanpwalsh, @JimMcHale, this should explain and fix the issue:

The accessibility whitelist seems to consistently get "stale" on new builds now, not allowing the old Easy Move+Resize permission entry to apply to the new binary.  This makes a lot of sense from a security perspective, but the user experience around it is not helpful at all.  You need to completely remove the old entry, then relaunch the new binary and toggle the new entry on.  Here's the detailed step-by-step that should get you up and running: https://github.com/dmarcotte/easy-move-resize/issues/79#issuecomment-1109070242

Optimistically closing this issue, but definitely drop another comment if this doesn't resolve the issue and we'll get to the bottom of it.
