### ISSUE TITLE
Issue with opening app after latest macOS release Ventura 13.3.1 (a)

### ISSUE THREAD

**Issue by nioakeim** [dmarcotte/easy-move-resize#92]
Hi Everyone,
this is the first time i write to this project however i am actually a user for many years and i really appreciate the time and effort putting into this project. it was actually my safeheaver when i moved my desktop from linux to mac.

I wanted to bring to your attention an issue i have with the latest release, since the latest security update of Ventura 13.3.1 (a). I cannot get past the control this computer from the privacy & security settings. Although it is allowed for the app to control this computer on the accessibility features, it seems its not enough.

Does anyone has the same issue?

**Comment by clauseggers** [comment]
Same issue. Something broke.

**Comment by nioakeim** [comment]
Hi! I found a solution to this problem. I removed the app from the privacy accessibility, by clicking on the - on the bottom, and then relaunched the app. Enabled the control and the app worked as expected. I am not sure what caused it. Hope this helps to your case

—
Best Regards,

Ioakeim Nikos
________________________________

**Comment by dmarcotte** [comment]
Thanks @nioakeim!  Glad that's sorted.

This is a common pitfall, documented in the [**troubleshooting** section of the Readme](https://github.com/dmarcotte/easy-move-resize#troubleshooting) of the readme, but it's totally understandable that you didn't see that—I'm only noting it here to give it some extra visibility, i.e. for folks who may land on this issue from search engines.

Wondering: did you use `brew` to upgrade?  Folks upgrading with `brew` have no chance to see the troubleshooting section, so we should likely also look into adding a helpful post-install message for these pitfalls.

**Comment by nioakeim** [comment]
Actually yes, I used brew for this. Thank you for noting the documentation side of the project. To be honest I should have seen this, but it caught me of guard this morning and did not have the time or patience to look around and that is why I quickly turned and asked within the project.

—
Best Regards,

Ioakeim Nikos
________________________________

**Comment by dmarcotte** [comment]
Thanks again, @nioakeim, and again: no worries about not seeing the doc!  That totally makes sense, especially given it was through `brew`.  I just created https://github.com/dmarcotte/easy-move-resize/issues/93 to see if we can improve this.
