### ISSUE TITLE
Not working on Ventura 13.4.1 

### ISSUE THREAD

**Issue by knoxsp** [dmarcotte/easy-move-resize#95]
Since doing an update to ventura 13.4.1, this is not longer working, citing that it needs to be updated as 
"Apple cannot check it for malicious software".

**Comment by dmarcotte** [comment]
Hi @knoxsp, thanks for filing this.  This is unfortunately a common roadblock—apologies you ran into it.  The fix described in the first bullet here should get you going: https://github.com/dmarcotte/easy-move-resize#troubleshooting

Going to optimistically close this, but feel free to let me know if there's further issues

**Comment by knoxsp** [comment]
I can confirm that the measures in the troubleshooting section helped (although I can't say which one exactly did the trick). Thanks for the prompt response.

**Comment by dmarcotte** [comment]
Great news, thanks @knoxsp!
